version: "2"
services:
  mysqldb:
    image: mysql:8.0.31
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Hong_Kong
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
